"""sales: disable nullable to total_profit

Revision ID: 1a317ebb201b
Revises: fda99dbcbfda
Create Date: 2025-12-04 13:55:15.962815

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1a317ebb201b'
down_revision: Union[str, None] = 'fda99dbcbfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
