"""sales: sale_date Timestamp to date

Revision ID: 7133b30ef069
Revises: c42eecc455e0
Create Date: 2025-12-03 09:32:11.499528

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7133b30ef069'
down_revision: Union[str, None] = 'c42eecc455e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'sale_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'sale_date',
               existing_type=sa.DATE(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
