"""update_future_preds_column_type

Revision ID: 91efd97ca61a
Revises: ffd8e21433d0
Create Date: 2025-12-07 15:55:22.013839

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '91efd97ca61a'
down_revision: Union[str, None] = 'ffd8e21433d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
