"""add_future_preds_to_restock_inference

Revision ID: 9ee97f5cdd5e
Revises: 1a317ebb201b
Create Date: 2025-12-07 15:13:26.742366

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ee97f5cdd5e'
down_revision: Union[str, None] = '1a317ebb201b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restock_inference', sa.Column('future_preds', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restock_inference', 'future_preds')
    # ### end Alembic commands ###
