"""sales: add total_profit col

Revision ID: fda99dbcbfda
Revises: 5abb9c57247d
Create Date: 2025-12-04 11:47:53.592244

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fda99dbcbfda'
down_revision: Union[str, None] = '5abb9c57247d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('total_profit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'total_profit')
    # ### end Alembic commands ###
