"""remove_predicted_restock_date_and_quantity_needed

Revision ID: ffd8e21433d0
Revises: 9ee97f5cdd5e
Create Date: 2025-12-07 15:53:57.306017

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffd8e21433d0'
down_revision: Union[str, None] = '9ee97f5cdd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restock_inference', 'quantity_needed')
    op.drop_column('restock_inference', 'predicted_restock_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restock_inference', sa.Column('predicted_restock_date', postgresql.ARRAY(sa.DATE()), autoincrement=False, nullable=False))
    op.add_column('restock_inference', sa.Column('quantity_needed', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
